version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    ports:
      - 8180:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/konveyor-realm.json
      DB_VENDOR: h2
    volumes:
      - ./konveyor-realm.json:/tmp/konveyor-realm.json:z
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  controls-db:
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: controls_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d controls_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  controls:
    image: quay.io/mrizzi/poc-controls:latest-native
    ports:
      - 8080:8080
    environment:
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://controls-db:5432/controls_db
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/auth/realms/konveyor
      QUARKUS_OIDC_CLIENT_ID: controls-api
      QUARKUS_OIDC_CREDENTIALS_SECRET: secret
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/controls/q/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      keycloak:
        condition: service_healthy
      controls-db:
        condition: service_healthy

  